# Generated by Django 2.2 on 2019-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('home', models.CharField(max_length=120)),
                ('away', models.CharField(max_length=120)),
            ],
        ),
    ]
